### ISSUE TITLE
Environmental Bisimulations for Probabilistic Higher-Order Languages

### ISSUE THREAD

**Issue by maxsnew** [gasche/popl2016-papers#45]
I found a link for this paper but it's not a direct pdf, instead it's a google docs viewer link. 

It's on this page: https://sites.google.com/site/valeriavignudelli/papers .

**Comment by gasche** [comment]
Seems okay, as there is an easy way for readers to download the PDF (I would frown at web readers that prevent offline download); we can format the link like `[preprint (weblink)](https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnx2YWxlcmlhdmlnbnVkZWxsaXxneDo0YzQ5ODFlN2MzODkzY2U4)`, or just link to the publication pages for more stability. Would you send a PR?
